In [0]:
import numpy as np
import pandas as pd
import nltk
nltk.download('punkt')
import re

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [0]:
df = pd.read_csv("tennis_articles_v4.csv")

In [0]:
df.head()

article_id  ...                                             source
0           1  ...  https://www.tennisworldusa.org/tennis/news/Mar...
1           2  ...  http://www.tennis.com/pro-game/2018/10/copil-s...
2           3  ...  https://scroll.in/field/899938/tennis-roger-fe...
3           4  ...  http://www.tennis.com/pro-game/2018/10/nishiko...
4           5  ...  https://www.express.co.uk/sport/tennis/1036101...

[5 rows x 3 columns]

In [0]:
df['article_text'][0]

"Maria Sharapova has basically no friends as tennis players on the WTA Tour. The Russian player has no problems in openly speaking about it and in a recent interview she said: 'I don't really hide any feelings too much. I think everyone knows this is my job here. When I'm on the courts or when I'm on the court playing, I'm a competitor and I want to beat every single person whether they're in the locker room or across the net.So I'm not the one to strike up a conversation about the weather and know that in the next few minutes I have to go and try to win a tennis match. I'm a pretty competitive girl. I say my hellos, but I'm not sending any players flowers as well. Uhm, I'm not really friendly or close to many players. I have not a lot of friends away from the courts.' When she said she is not really close to a lot of players, is that something strategic that she is doing? Is it different on the men's tour than the women's tour? 'No, not at all. I think just because you're in the same 

In [0]:
len(df['article_text'])

8

In [0]:
from nltk.tokenize import sent_tokenize
# print(sent_tokenize(df['article_text'][0]))
# se = sent_tokenize(df['article_text'][0])
# print(len(se))
articles = []
for article in df['article_text']:
  articles.append(sent_tokenize(article))

In [0]:
articles[0]

['Maria Sharapova has basically no friends as tennis players on the WTA Tour.',
 "The Russian player has no problems in openly speaking about it and in a recent interview she said: 'I don't really hide any feelings too much.",
 'I think everyone knows this is my job here.',
 "When I'm on the courts or when I'm on the court playing, I'm a competitor and I want to beat every single person whether they're in the locker room or across the net.So I'm not the one to strike up a conversation about the weather and know that in the next few minutes I have to go and try to win a tennis match.",
 "I'm a pretty competitive girl.",
 "I say my hellos, but I'm not sending any players flowers as well.",
 "Uhm, I'm not really friendly or close to many players.",
 "I have not a lot of friends away from the courts.'",
 'When she said she is not really close to a lot of players, is that something strategic that she is doing?',
 "Is it different on the men's tour than the women's tour?",
 "'No, not at all.

In [0]:
sentences = []
for article in articles:
  for sent in article:
    sentences.append(sent)

In [0]:
print(type(sentences))
print(len(sentences))


<class 'list'>
119


In [0]:
sentences

['Maria Sharapova has basically no friends as tennis players on the WTA Tour.',
 "The Russian player has no problems in openly speaking about it and in a recent interview she said: 'I don't really hide any feelings too much.",
 'I think everyone knows this is my job here.',
 "When I'm on the courts or when I'm on the court playing, I'm a competitor and I want to beat every single person whether they're in the locker room or across the net.So I'm not the one to strike up a conversation about the weather and know that in the next few minutes I have to go and try to win a tennis match.",
 "I'm a pretty competitive girl.",
 "I say my hellos, but I'm not sending any players flowers as well.",
 "Uhm, I'm not really friendly or close to many players.",
 "I have not a lot of friends away from the courts.'",
 'When she said she is not really close to a lot of players, is that something strategic that she is doing?',
 "Is it different on the men's tour than the women's tour?",
 "'No, not at all.

In [0]:
sentences[:6]

['Maria Sharapova has basically no friends as tennis players on the WTA Tour.',
 "The Russian player has no problems in openly speaking about it and in a recent interview she said: 'I don't really hide any feelings too much.",
 'I think everyone knows this is my job here.',
 "When I'm on the courts or when I'm on the court playing, I'm a competitor and I want to beat every single person whether they're in the locker room or across the net.So I'm not the one to strike up a conversation about the weather and know that in the next few minutes I have to go and try to win a tennis match.",
 "I'm a pretty competitive girl.",
 "I say my hellos, but I'm not sending any players flowers as well."]

In [0]:
import string
from string import digits
exclude1 = set(string.punctuation)
exclude2 = set(string.digits)
sentences = pd.Series(sentences).apply(lambda x: ''.join(ch for ch in x if ch not in exclude1))
sentences = pd.Series(sentences).apply(lambda x: ''.join(ch for ch in x if ch not in exclude2))

In [0]:
sentences = pd.Series(sentences).apply(lambda x: re.sub("[?=.\"][?=.\']", '', x))

In [0]:
sentences = pd.Series(sentences).apply(lambda x: x.lower())

In [0]:
sentences[0]

'maria sharapova has basically no friends as tennis players on the wta tour'

In [0]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

In [0]:
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [0]:
# sentences = pd.Series(sentences).apply(lambda x: ''.join(ch + " " for ch in x.split() if ch not in stop_words))
sentences = pd.Series(sentences).apply(lambda x: x.strip() )

In [0]:
sentences[0].split()[0]

'maria'

In [0]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove*.zip

--2020-02-06 13:21:43--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2020-02-06 13:21:43--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2020-02-06 13:21:44--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6

In [0]:
word_embeddings = {}
f = open('glove.6B.100d.txt', encoding='utf-8')
for line in f:
  values = line.split()
  word = values[0]
  coefs = np.asarray(values[1:], dtype='float32')
  word_embeddings[word] = coefs
f.close()

In [0]:
print(word_embeddings['the'].shape)
print( type(word_embeddings['the']) )

(100,)
<class 'numpy.ndarray'>


In [0]:
len(word_embeddings.keys())

400000

In [0]:
# sum_vec = np.zeros((100,))
# type(sum_vec)

In [0]:
# Sentence vector
sent_embedding = {}
for sentence in sentences:
  sum_vec = np.zeros((100, ))
  # print(sum_vec.dtype)
  # print(type(sum_vec))
  for word in sentence.split(): 
    if word in word_embeddings.keys():
      sum_vec = np.add(sum_vec, word_embeddings[word])

  sum_vec = np.true_divide(sum_vec, len(sentence.split()) )
  sent_embedding[sentence] = sum_vec 

In [0]:
sent_embedding.keys()

dict_keys(['maria sharapova has basically no friends as tennis players on the wta tour', 'the russian player has no problems in openly speaking about it and in a recent interview she said i dont really hide any feelings too much', 'i think everyone knows this is my job here', 'when im on the courts or when im on the court playing im a competitor and i want to beat every single person whether theyre in the locker room or across the netso im not the one to strike up a conversation about the weather and know that in the next few minutes i have to go and try to win a tennis match', 'im a pretty competitive girl', 'i say my hellos but im not sending any players flowers as well', 'uhm im not really friendly or close to many players', 'i have not a lot of friends away from the courts', 'when she said she is not really close to a lot of players is that something strategic that she is doing', 'is it different on the mens tour than the womens tour', 'no not at all', 'i think just because youre i

In [0]:
sent_embedding[sentences[0]].shape

(100,)

In [0]:
counter = 0
for sentence in sentences:
  counter = counter + 1
  if sentence=='speaking at the swiss indoors tournament where he will play in sundays final against romanian qualifier marius copil the world number three said that given the impossibly short time frame to make a decision he opted out of any commitment':
    print (counter)

31


In [0]:
len(sentences)

119

In [0]:
similarity_mat = np.zeros(( len(sentences), len(sentences)))

In [0]:
def cosine_similarity(sent1, sent2, sent_embedding):
  prod = np.linalg.norm(sent_embedding[sent1])  *  np.linalg.norm(sent_embedding[sent2])
  numerator = np.dot(  sent_embedding[sent1],  sent_embedding[sent2]  )
  return numerator/prod

In [0]:
for i in range(len(sentences)):
  for j in range(i, len(sentences), 1):
    similarity_mat[i][j] = cosine_similarity( sentences[i], sentences[j], sent_embedding)
    similarity_mat[j][i] = similarity_mat[i][j]

In [0]:
print(similarity_mat)

[[1.         0.88191321 0.8373999  ... 0.891789   0.85290144 0.88390234]
 [0.88191321 1.         0.93075035 ... 0.95100288 0.93503689 0.96660122]
 [0.8373999  0.93075035 1.         ... 0.94383974 0.87909084 0.90166331]
 ...
 [0.891789   0.95100288 0.94383974 ... 1.         0.92247169 0.96141665]
 [0.85290144 0.93503689 0.87909084 ... 0.92247169 1.         0.93247135]
 [0.88390234 0.96660122 0.90166331 ... 0.96141665 0.93247135 1.        ]]


In [0]:
import networkx as nx
nx_graph = nx.from_numpy_array(similarity_mat)

In [0]:
scores = nx.pagerank(nx_graph)

In [0]:
# scores

{0: 0.008353175379230986,
 1: 0.008535759451247594,
 2: 0.008088397542873955,
 3: 0.008745187837063578,
 4: 0.007332076812332743,
 5: 0.008335320406412652,
 6: 0.008244334441958164,
 7: 0.008587994378121638,
 8: 0.008547878430330303,
 9: 0.008387923895840112,
 10: 0.008412872115956926,
 11: 0.008486996765850335,
 12: 0.008107926462602225,
 13: 0.008404779288963101,
 14: 0.008453753885170704,
 15: 0.008557817811799132,
 16: 0.008308541800953752,
 17: 0.008142061474747912,
 18: 0.008501479594042946,
 19: 0.008565574435853707,
 20: 0.008543543708416548,
 21: 0.00833957386917139,
 22: 0.008378485982351443,
 23: 0.008501864753095539,
 24: 0.008396821469923871,
 25: 0.007569537710836507,
 26: 0.00832876692993733,
 27: 0.008525393778305896,
 28: 0.00862601034509713,
 29: 0.008670193951953384,
 30: 0.008745726937411012,
 31: 0.008562448511187546,
 32: 0.008362474498535106,
 33: 0.00849203567151222,
 34: 0.008590224315737615,
 35: 0.008556415958219658,
 36: 0.008154066573314632,
 37: 0.00858055

In [0]:
ranked_sentences = sorted(((scores[i],s) for i,s in enumerate(sentences)), reverse=True)

In [0]:
for i in range(10):
  print(ranked_sentences[i][1])

speaking at the swiss indoors tournament where he will play in sundays final against romanian qualifier marius copil the world number three said that given the impossibly short time frame to make a decision he opted out of any commitment
when im on the courts or when im on the court playing im a competitor and i want to beat every single person whether theyre in the locker room or across the netso im not the one to strike up a conversation about the weather and know that in the next few minutes i have to go and try to win a tennis match
major players feel that a big event in late november combined with one in january before the australian open will mean too much tennis and too little rest
i felt like the best weeks that i had to get to know players when i was playing were the fed cup weeks or the olympic weeks not necessarily during the tournaments
federer said earlier this month in shanghai in that his chances of playing the davis cup were all but nonexistent
not always but i really f

In [0]:
type(ranked_sentences)

list